// src/lib/schemas/credential.schema.ts
import { z } from "zod";

// Strict W3C format generated by the backend
export const W3CCredentialSchema = z.object({
  id: z.string(),
  type: z.array(z.string()),
  issuer: z.string(),
  issuanceDate: z.string(),
  credentialSubject: z.object({
    id: z.string()
  }).passthrough(),
  proof: z.object({
    type: z.string(),
    verificationMethod: z.string(),
    signatureValue: z.string()
  })
}).passthrough();

// Dummy / Legacy format used for manual testing
export const DummyCredentialSchema = z.object({
  id: z.string(),
  issuer: z.string(),
  recipient: z.string().optional(),
  course: z.string().optional(),
  issuedAt: z.string().optional(),
  signature: z.string().optional()
}).passthrough();

// Accept both so the frontend doesn't crash on manual test files, 
// allowing the backend to properly reject invalid cryptographic signatures.
export const CredentialSchema = z.union([W3CCredentialSchema, DummyCredentialSchema]);

export type ValidCredential = z.infer<typeof CredentialSchema>;